---
steps:

  # this uses a submodule, need to pull it down in cloudbuild
  - name: gcr.io/cloud-builders/git
    args: ['submodule', 'update', '--init', '--recursive']

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "./infra/grafana/backup/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/grafana-backup:production",
        "./infra/grafana/backup/",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/grafana-backup:production"]

images:
  - gcr.io/$PROJECT_ID/grafana-backup:production
