---
steps:

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "./Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/grafana-backup:production",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/grafana-backup:production"]

images:
  - gcr.io/$PROJECT_ID/grafana-backup:production
